### ISSUE TITLE
🔰 [Initiative] Developer Awareness / Technical Content

### ISSUE THREAD

**Issue by thisisjoshford** [near/Pagoda-Roadmap#139]
### Description
Creating engaging technical content centered around problems that open web tech solves. 

Blog posts:
- New feature releases w/ code examples
- Past, present, & future of NEAR's / Pagoda's tech stack

### Resources

```[tasklist]
### Related Epics
- [ ] https://github.com/near/docs/issues/1767
- [ ] https://github.com/near/DX/issues/3
```

**Comment by Universe-stack** [comment]
Hi @thisisjoshford , I'm a big fan of Near and the general Near ecosystem. I've been an avid holder of near tokens for a long time and have also helped work on a mini Near powered web dapp.

I ask for a chance to contribute to Near's technical content. It would really be an honor to do so.

Thank you.

**Comment by thisisjoshford** [comment]
> Hi @thisisjoshford , I'm a big fan of Near and the general Near ecosystem. I've been an avid holder of near tokens for a long time and have also helped work on a mini Near powered web dapp.
> 
> I ask for a chance to contribute to Near's technical content. It would really be an honor to do so.
> 
> Thank you.

Hey there @Universe-stack ! We're just about to kick start this initiative with another contributor. Happy to include more community involvement here and would love to know more about what areas you would like to create content for.
